fixtures:
  repositories:
    "stdlib":
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "5.0.0"
    "staging":
      repo: "https://github.com/nanliu/puppet-staging.git"
      ref: "1.0.4"
  symlinks:
    "plexmediaserver": "#{source_dir}"
