language: ruby
script:
  - "bundle exec puppet --version"
  - "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
  - "bundle exec rake lint"
  - "bundle exec rake syntax"
rvm:
 - 2.7.0
 - 3.4.1
matrix:
  fast_finish: true
